//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Post
    {
        public System.Guid id { get; set; }
        public System.Guid authorId { get; set; }
        [Required(ErrorMessage = "Titolo mancante.")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Il titolo deve essere compreso fra 5 e 100 caratteri.")]
        [Remote("CheckForDuplication", "Post")]
        public string title { get; set; }
        [Required(ErrorMessage="Articolo mancante.")]
        [StringLength(int.MaxValue, MinimumLength = 5, ErrorMessage = "Il post deve essere almeno di 5 caratteri.")]
        public string body { get; set; }
        
        [DisplayFormat(DataFormatString = "Creato il {0:MM/dd/yy @ H:mm}")]
        public System.DateTime createdAt { get; set; }

        [DisplayFormat(DataFormatString = "Aggiornato il {0:MM/dd/yy @ H:mm}")]
        public System.DateTime updatedAt { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
